config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
  	root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]

  def index
  	@notes = Note.where(user_id: current_user)
  end

  def show

  end


  def new
  	@note = current_user.notes.build
  end


  def create
    @note = current_user.notes.build(note_params)

  	if @note.save
  	  redirect_to @note
  	else
  	  render 'new'
  	end
  end

  def edit

  end

  def update
  	if @note.update(note_params)
  		redirect_to @note
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@note.destroy
  	redirect_to notes_path
  end


  private

  def find_note
  	@note = Note.find(params[:id])
  end

  def note_params
  	params.require(:note).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mynote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/notes/edit.html.haml
%h1 Edit page

= render 'form'

= link_to "Cancel", note_path

app/views/notes/index.html.haml
- @notes.each do |note|
  %h2= link_to note.title, note
  %p= time_ago_in_words(note.created_at)

= link_to "New note",new_note_path

app/views/notes/new.html.haml
%h1 Add a new note

= render "form"

app/views/notes/show.html.haml
%h1= @note.title
%p= @note.content

= link_to "All Notes", notes_path
= link_to "Edit", edit_note_path(@note)
= link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure"}

app/views/welcome/index.html.haml
%h1 This is the index page